### ISSUE TITLE
Passkey integration

### ISSUE THREAD

**Issue by kissu** [atinux/nuxt-auth-utils#119]
Hey! Not sure how hard it is to implement some Passkeys or even if it's planned but creating the issue for it. 🙂

**Comment by Gerbuuun** [comment]
I'm almost done with my implementation but it does have a dependency on pilcrow's `oslo` package.
I could create a PR to this repo within a few days.

I think `oslo` has very good validation functions but this module should also have some utils that create the keys / challenges etc.

I think the minimum would be:
- A composable which handles key and signature creation on client side
- Nitro endpoint that returns credential options.
- Server util for authenticator validation (just like `oslo`)
- Server util for credential validation (just like `oslo`)

@Atinux what do you think about the dependency on `oslo`?
Maybe it's better to copy the necessary functions (with reference) instead of depending on the whole package

**Comment by EnjoyKojima** [comment]
Hello!!
By olso, do you mean [this package](https://github.com/oslo-project)?
I look forward to your PR being merged!

**Comment by Gerbuuun** [comment]
Yes, the `webauthn` part has the necessary cryptographic key validation functions.

**Comment by Atinux** [comment]
If we can avoid importing `oslo` but having the utilities into this package it would be great so we can be sure that it works on the edge runtime too.

Happy to see your PR @Gerbuuun ❤
