### ISSUE TITLE
email/username + password auth?

### ISSUE THREAD

**Issue by they-cloned-me** [Atinux/nuxt-auth-utils#16]
How can we extend this to support username+password auth?
I understand it may involve some kind of db configuration to store user data

**Comment by Atinux** [comment]
Just create your own API route, call your database and then use `setUserSession(event, ...)` in it.

This module won't support this feature but instead we can think of writing down a "recipe" on how to do this.

**Comment by PGLongo** [comment]
@Atinux the plan is to support only OAuth? In that case maybe the name of the module should be nuxt-oauth-utils.

I think that JWT + Basic Auth could be interesting

**Comment by angelhdzmultimedia** [comment]
I implemented Steam Strategy yesterday and Local Strategy today, Steam uses OpenID instead of OAuth,
my local strategy requires a validate (for login) and onRegister (for register) handlers in the `auth.localEventHandler`, in which you can place the logic for the database using the username/password for validate and username/data for register,   and I was very hyped, but after the replies above I feel discouraged to continue now.

My suggestion was to replace the oauth namespace with just auth, so that local and steam and other non oauth strategies could be added.


The best approach is taking inspiration from Passport.js, allowing any kind of strategy, but it seems there's a strong decision to stick to OAuth, so I will keep using Passport.js or create my own library.

This and no support for SPA. It's unfortunate. Cheers. 👋

**Comment by they-cloned-me** [comment]
> Just create your own API route, call your database and then use `setUserSession(event, ...)` in it.
> 
> This module won't support this feature but instead we can think of writing down a "recipe" on how to do this.

Sounds good, and yes, I think `nuxt-oauth-utils` will convey a better meaning to what the module does.

**Comment by they-cloned-me** [comment]
I believe this feature may be landing soon. 🤩

I recently saw some discussion about `bcrypt-edge` by @atinux.
