### ISSUE TITLE
How to block/suspend users?

### ISSUE THREAD

**Issue by ilyabumblebee** [Atinux/nuxt-auth-utils#68]
Not a problem, but do you have any suggestions for blocking users by invalidating all tokens and preventing future sign-ins in a clean way?

**Comment by Gerbuuun** [comment]
You could hook into the session fetch and then check if the user is blocked by using a database or KV store.

Example: `~/server/plugins/check-blocked.ts`
```ts
export default defineNitroPlugin(() => {
  sessionHooks.hook('fetch', async (session, event) => {
    // Check if user is blocked (in DB or KV) using session.user.id for example

    // If blocked clear the session and throw an error (or redirect to sign-in page)
    if (blocked) {
      await clearUserSession(event);

      // Throw an error (401 probably)
      throw createError({ ... })
      // or a redirect?
      return sendRedirect(event, '/sign-in');
    }
  });
});
```

Not sure if it works because it only checks on session fetch (so first page load?). I based it on the [readme](https://github.com/Atinux/nuxt-auth-utils?tab=readme-ov-file#extend-session)

In api routes you could create a [middleware](https://nitro.unjs.io/guide/routing#middleware): `~/server/middleware/check-blocked.ts`
```ts
export default defineEventHandler(async (event) => {
  const session = await requireUserSession(event);
  // Same check as in example above
}
```

I hope this gives you enough information?

**Comment by ilyabumblebee** [comment]
Thanks!
